name: Test

on:
    push:
        branches: [ development, main ]
    pull_request:
        branches: [ development, main ]
    schedule:
        -   cron: 0 3 * * 1,3,5
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ 7.4, 8.0, 8.1 ]
            fail-fast: false
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@2.10.0
                with:
                    php-version: ${{ matrix.php }}
                    tools: composer:v2
            -   name: Install dependencies
                run: composer update
            -   name: Run test suite
                run: composer run test
